#!/bin/bash

# Video Queue System
# CEO-approved approach: Queue scripts, manual render trigger

QUEUE_DIR="/root/.openclaw/workspace/agents-output/video-queue"
mkdir -p "$QUEUE_DIR"

# Generate video script from research
generate_script() {
    local topic="$1"
    local format="$2"  # short or long
    
    cat > "$QUEUE_DIR/script-$(date +%s).json" << EOF
{
  "topic": "$topic",
  "format": "$format",
  "script": "Generated by claw-video-editor",
  "status": "pending",
  "created": "$(date -Iseconds)"
}
EOF
    echo "Script queued: $topic ($format)"
}

# Main: Queue videos based on research
main() {
    echo "🎬 Video Editor (CEO Mode)"
    
    # Check for research data
    RESEARCH_FILE=$(ls -t /root/.openclaw/workspace/agents-output/research/trends-*.json 2>/dev/null | head -1)
    
    if [ -f "$RESEARCH_FILE" ]; then
        echo "Found research: $RESEARCH_FILE"
        
        # Queue 1 short (quick to render)
        generate_script "AI Agents Explained" "short"
        
        # Queue 1 long-form (for manual render)
        generate_script "Top Tech Trends 2025" "long"
        
        echo "✅ 2 videos queued. Use 'render-now.sh' to render."
    else
        echo "No research found. Skipping."
    fi
}

main
