import { VulnerabilityInput, ScanResult, CodeContext } from '../types';

/**
 * Security Scanner Engine
 * Performs static analysis on code to detect vulnerabilities
 * MVP uses pattern-based detection (Semgrep-style rules)
 */
export class SecurityScanner {
  private rules: SecurityRule[];

  constructor() {
    this.rules = this.loadRules();
  }

  /**
   * Scan code for security vulnerabilities
   */
  async scan(code: string, language: string, context: CodeContext): Promise<ScanResult> {
    const vulnerabilities: VulnerabilityInput[] = [];

    for (const rule of this.rules) {
      if (rule.languages.includes(language) || rule.languages.includes('*')) {
        const matches = this.applyRule(code, rule, context);
        vulnerabilities.push(...matches);
      }
    }

    // Deduplicate by line number and rule
    const uniqueVulns = this.deduplicate(vulnerabilities);

    return {
      vulnerabilities: uniqueVulns,
      summary: this.calculateSummary(uniqueVulns),
    };
  }

  /**
   * Detect if code was AI-generated
   */
  async detectAIGenerated(code: string): Promise<{ isAIGenerated: boolean; confidence: number }> {
    const patterns = [
      /\/\/ Generated by (Copilot|Cursor|GitHub Copilot|AI)/i,
      /\/\/ Generated code/i,
      /\/\/ AI-generated/i,
      /\*\s*Generated by (Copilot|Cursor)/i,
    ];

    for (const pattern of patterns) {
      if (pattern.test(code)) {
        return { isAIGenerated: true, confidence: 0.95 };
      }
    }

    // Heuristic: Check for overly generic patterns common in AI code
    const genericPatterns = [
      /function\s+\w+\s*\([^)]*\)\s*{\s*\/\/ TODO/i,
      /\/\/ Implementation goes here/i,
      /\/\/ Add your code here/i,
    ];

    for (const pattern of genericPatterns) {
      if (pattern.test(code)) {
        return { isAIGenerated: true, confidence: 0.7 };
      }
    }

    return { isAIGenerated: false, confidence: 0.5 };
  }

  private loadRules(): SecurityRule[] {
    return [
      // OWASP A01: Broken Access Control
      {
        id: 'ai-hardcoded-secret',
        name: 'Hardcoded Secret in AI-Generated Code',
        languages: ['javascript', 'typescript', 'python', 'java', 'go'],
        severity: 'critical',
        cweId: 'CWE-798',
        owaspCategory: 'A07:2021 - Identification and Authentication Failures',
        patterns: [
          /(?:const|let|var|final|String)\s+(?:api[_-]?key|password|secret|token)\s*=\s*["'][^"']{8,}["']/i,
          /(?:password|secret|token)\s*:\s*["'][^"']{8,}["']/i,
        ],
        message: 'Potential hardcoded secret detected in AI-generated code. Move to environment variables.',
        suggestedFix: 'Use environment variables: const apiKey = process.env.API_KEY;',
      },
      // OWASP A03: Injection
      {
        id: 'ai-sql-injection',
        name: 'SQL Injection in AI-Generated Code',
        languages: ['javascript', 'typescript', 'python', 'java'],
        severity: 'critical',
        cweId: 'CWE-89',
        owaspCategory: 'A03:2021 - Injection',
        patterns: [
          /(?:query|sql)\s*=\s*[`"'].*\$\{[^}]+\}.*[`"']/,
          /(?:query|sql)\s*=\s*["'].*\+\s*\w+\s*\+/,
          /execute\s*\(\s*[^,]*\+\s*\w+/,
        ],
        message: 'Potential SQL injection vulnerability. Use parameterized queries.',
        suggestedFix: 'Use parameterized queries: db.query("SELECT * FROM users WHERE id = ?", [userId])',
      },
      // OWASP A03: Injection (NoSQL)
      {
        id: 'ai-nosql-injection',
        name: 'NoSQL Injection in AI-Generated Code',
        languages: ['javascript', 'typescript'],
        severity: 'high',
        cweId: 'CWE-943',
        owaspCategory: 'A03:2021 - Injection',
        patterns: [
          /find\s*\(\s*\{\s*\$where\s*:/,
          /\$where\s*:\s*["'].*\+\s*\w+/,
        ],
        message: 'Potential NoSQL injection. Avoid using $where operator with user input.',
        suggestedFix: 'Use explicit query operators without $where',
      },
      // XSS
      {
        id: 'ai-xss-innerhtml',
        name: 'XSS via innerHTML in AI-Generated Code',
        languages: ['javascript', 'typescript'],
        severity: 'high',
        cweId: 'CWE-79',
        owaspCategory: 'A03:2021 - Injection',
        patterns: [
          /\.innerHTML\s*=\s*[^;]+(?:user|input|data|param)/i,
          /dangerouslySetInnerHTML\s*=\s*\{\s*__html\s*:\s*[^}]+(?:user|input|data|param)/i,
        ],
        message: 'Potential XSS vulnerability. User input rendered directly to DOM.',
        suggestedFix: 'Use textContent instead of innerHTML, or sanitize HTML using DOMPurify',
      },
      // Path Traversal
      {
        id: 'ai-path-traversal',
        name: 'Path Traversal in AI-Generated Code',
        languages: ['javascript', 'typescript', 'python', 'java'],
        severity: 'high',
        cweId: 'CWE-22',
        owaspCategory: 'A01:2021 - Broken Access Control',
        patterns: [
          /fs\.(?:readFile|writeFile|open)\s*\(\s*[^,)]*\+\s*(?:user|input|req)/,
          /open\s*\(\s*[^,)]*(?:user|input|req)/,
        ],
        message: 'Potential path traversal vulnerability. User input used in file paths.',
        suggestedFix: 'Validate and sanitize file paths, use path.join() with allowlist',
      },
      // Insecure Randomness
      {
        id: 'ai-insecure-random',
        name: 'Insecure Randomness in AI-Generated Code',
        languages: ['javascript', 'typescript', 'python'],
        severity: 'medium',
        cweId: 'CWE-338',
        owaspCategory: 'A02:2021 - Cryptographic Failures',
        patterns: [
          /Math\.random\s*\(\s*\)/,
          /random\.random\s*\(\s*\)/,
        ],
        message: 'Math.random() is not cryptographically secure. Use crypto.randomBytes() for security purposes.',
        suggestedFix: 'Use crypto.randomBytes() or crypto.randomUUID() for security-sensitive operations',
      },
      // Weak Cryptography
      {
        id: 'ai-weak-crypto',
        name: 'Weak Cryptographic Algorithm',
        languages: ['javascript', 'typescript', 'python', 'java'],
        severity: 'high',
        cweId: 'CWE-327',
        owaspCategory: 'A02:2021 - Cryptographic Failures',
        patterns: [
          /createHash\s*\(\s*["']md5["']\s*\)/,
          /createHash\s*\(\s*["']sha1["']\s*\)/,
          /(?:SHA1|MD5)\s*\(/,
        ],
        message: 'Weak hashing algorithm detected. MD5 and SHA1 are cryptographically broken.',
        suggestedFix: 'Use SHA-256 or bcrypt for passwords: crypto.createHash("sha256")',
      },
      // Command Injection
      {
        id: 'ai-command-injection',
        name: 'Command Injection in AI-Generated Code',
        languages: ['javascript', 'typescript', 'python'],
        severity: 'critical',
        cweId: 'CWE-78',
        owaspCategory: 'A03:2021 - Injection',
        patterns: [
          /exec\s*\(\s*[`"'][^`"']*\$\{/,
          /execSync\s*\(\s*["'][^"']*\+\s*\w+/,
          /child_process.*exec.*\+\s*(?:user|input|req)/,
        ],
        message: 'Potential command injection. User input passed to shell command.',
        suggestedFix: 'Use execFile() with array arguments instead of string concatenation',
      },
      // Insecure Deserialization
      {
        id: 'ai-insecure-deserialization',
        name: 'Insecure Deserialization',
        languages: ['javascript', 'typescript', 'python'],
        severity: 'high',
        cweId: 'CWE-502',
        owaspCategory: 'A08:2021 - Software and Data Integrity Failures',
        patterns: [
          /JSON\.parse\s*\(\s*(?:user|input|req|body)/,
          /eval\s*\(\s*(?:user|input|req|body)/,
          /new Function\s*\(\s*(?:user|input|req|body)/,
        ],
        message: 'Potential insecure deserialization. User input parsed without validation.',
        suggestedFix: 'Validate and sanitize input before parsing, use a schema validator',
      },
      // SSRF
      {
        id: 'ai-ssrf',
        name: 'Server-Side Request Forgery (SSRF)',
        languages: ['javascript', 'typescript', 'python'],
        severity: 'high',
        cweId: 'CWE-918',
        owaspCategory: 'A10:2021 - Server-Side Request Forgery',
        patterns: [
          /fetch\s*\(\s*(?:user|input|req)\./,
          /axios\.(?:get|post)\s*\(\s*(?:user|input|req)\./,
          /request\s*\(\s*(?:user|input|req)\./,
        ],
        message: 'Potential SSRF vulnerability. User input used in outbound request.',
        suggestedFix: 'Validate URLs against allowlist, avoid passing user input directly to request libraries',
      },
      // Insecure CORS
      {
        id: 'ai-insecure-cors',
        name: 'Insecure CORS Configuration',
        languages: ['javascript', 'typescript'],
        severity: 'medium',
        cweId: 'CWE-942',
        owaspCategory: 'A05:2021 - Security Misconfiguration',
        patterns: [
          /Access-Control-Allow-Origin\s*:\s*["']\*["']/,
          /cors\s*\(\s*\{\s*origin\s*:\s*["']\*["']/,
        ],
        message: 'Permissive CORS policy allows any origin to access resources.',
        suggestedFix: 'Specify explicit allowed origins instead of wildcard (*)',
      },
      // Missing Auth Check
      {
        id: 'ai-missing-auth',
        name: 'Missing Authentication Check',
        languages: ['javascript', 'typescript', 'python'],
        severity: 'high',
        cweId: 'CWE-306',
        owaspCategory: 'A07:2021 - Identification and Authentication Failures',
        patterns: [
          /(?:app\.)?(?:get|post|put|delete|patch)\s*\(\s*["']\/(?:admin|api\/admin|users|settings)/i,
        ],
        message: 'Potentially sensitive endpoint without visible authentication check.',
        suggestedFix: 'Add authentication middleware before route handler',
      },
    ];
  }

  private applyRule(code: string, rule: SecurityRule, context: CodeContext): VulnerabilityInput[] {
    const vulnerabilities: VulnerabilityInput[] = [];
    const lines = code.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      
      for (const pattern of rule.patterns) {
        if (pattern.test(line)) {
          vulnerabilities.push({
            ruleId: rule.id,
            severity: rule.severity,
            filePath: context.filePath,
            lineStart: i + 1,
            lineEnd: i + 1,
            message: rule.message,
            suggestedFix: rule.suggestedFix,
            cweId: rule.cweId,
            owaspCategory: rule.owaspCategory,
          });
        }
      }
    }

    return vulnerabilities;
  }

  private deduplicate(vulns: VulnerabilityInput[]): VulnerabilityInput[] {
    const seen = new Set<string>();
    return vulns.filter(vuln => {
      const key = `${vuln.ruleId}:${vuln.filePath}:${vuln.lineStart}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }

  private calculateSummary(vulns: VulnerabilityInput[]): ScanResult['summary'] {
    return {
      total: vulns.length,
      critical: vulns.filter(v => v.severity === 'critical').length,
      high: vulns.filter(v => v.severity === 'high').length,
      medium: vulns.filter(v => v.severity === 'medium').length,
      low: vulns.filter(v => v.severity === 'low').length,
    };
  }
}

interface SecurityRule {
  id: string;
  name: string;
  languages: string[];
  severity: 'critical' | 'high' | 'medium' | 'low';
  cweId: string;
  owaspCategory: string;
  patterns: RegExp[];
  message: string;
  suggestedFix?: string;
}

export const securityScanner = new SecurityScanner();
